name: Run Node.js Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js environment with version 20
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Use Node.js version 20

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run the server.js script
    - name: Run server.js
      run: |
        node server.js &
        echo "Server is running..."
        while true; do sleep 30m; done
